version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: Jeopardy_SQL1
      MYSQL_DATABASE: Jeopardy_db
    ports:
      - "3310:3306"

  admin:
    image: adminer
    ports:
      - "8080:8080"

